name: Hello World

# Events

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:


# Workflow / jobs

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: whoami
        shell: bash